name: Approver

on:
  workflow_dispatch:
    inputs:
      prnumber:
        description: "Input Approve PR ID"     
        required: true
        default: "-1"

jobs:
  Approver:
    name: Approver
    runs-on: ubuntu-latest
    steps:
      - name: "Approve Pull Request #${{ inputs.prnumber }}"
        uses: juliangruber/approve-pull-request-action@v2.0.4
        with:
          github-token: ${{ secrets.EFI_BOT_TOKEN }}
          number: ${{ inputs.prnumber }}

      - name: "UnLabel PR #${{ inputs.prnumber }}"
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: "AutoSquash-Crowdin"
          github_token: ${{ secrets.EFI_BOT_TOKEN }}
          number: ${{ inputs.prnumber }}

      - name: Sleeping 1m
        run: sleep 1m

      - name: "Label PR #${{ inputs.prnumber }}"
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: "AutoSquash-Crowdin"
          github_token: ${{ secrets.EFI_BOT_TOKEN }}
          number: ${{ inputs.prnumber }}
