name: AutoSquash
on:
  check_run:
    types:
      - completed
  pull_request:
    types:
      - closed
      - labeled
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  SquashCrowdin:
    name: Squash Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Check Label
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: "MergeTranslate"

      - name: Squash Merge
        uses: pascalgn/automerge-action@v0.14.3
        if: steps.haslabel.outputs.labeled-MergeTranslate
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "MergeTranslate"
          MERGE_REMOVE_LABELS: "MergeTranslate"
          MERGE_COMMIT_MESSAGE: "ci: Crowdin Update #{pullRequest.number}"
          MERGE_REQUIRED_APPROVALS: 0
          MERGE_DELETE_BRANCH: true
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"

  SquashRoadMap:
    name: Squash RoadMap
    runs-on: ubuntu-latest
    steps:
      - name: Check Label
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: "MergeRoadMap"

      - name: Squash Merge
        uses: pascalgn/automerge-action@v0.14.3
        if: steps.haslabel.outputs.labeled-MergeRoadMap
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "MergeRoadMap"
          MERGE_REMOVE_LABELS: "MergeRoadMap"
          MERGE_COMMIT_MESSAGE: "ci: RoadMap Update #{pullRequest.number}"
          MERGE_REQUIRED_APPROVALS: 1
          MERGE_DELETE_BRANCH: true
          MERGE_METHOD: "squash"
          MERGE_FORKS: "false"
          UPDATE_LABELS: ""
          UPDATE_METHOD: "rebase"
