name: AutoSquash
on:
  check_run:
    types:
      - completed
  pull_request:
    types:
      - labeled
  pull_request_review:
    types:
      - submitted
  status: {}

jobs:
  SuqashAutomated:
    name: ${{ matrix.name }} Squash
    runs-on: ubuntu-latest
    if: |
      github.repository == 'SlimeTraditionalTranslation/Misc-Translate'
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "Crowdin"
            label: "AutoSquash_Crowdin"
            commit_message: "ci(Crowdin): Automatic update (#{pullRequest.number})"
          - name: "RoadMap"
            label: "AutoSquash_RoadMap"
            commit_message: "ci(RoadMap): Automatic update (#{pullRequest.number})"
          - name: "Action"
            label: "AutoSquash_Action"
            commit_message: "ci(Action): Automatic update (#{pullRequest.number})"

    steps:
      - name: Checking Label
        id: haslabel
        uses: DanielTamkin/HasLabel@v1.0.4
        with:
          contains: ${{ matrix.label }}

      - name: Check PR labels action step
        id: check_pr_labels
        uses: shioyang/check-pr-labels-on-push-action@v1.0.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ matrix.label }}

      - name: See result
        run: echo "${{ steps.check_pr_labels.outputs.result }}"

      # - name: Wait 30s Crowdin finish add all translate
      #   if: steps.haslabel.outputs.labeled-AutoSquash_Crowdin
      #   run: sleep 30s

      # - name: Auto Crowdin PR approve
      #   if: steps.haslabel.outputs.labeled-AutoSquash_Crowdin
      #   uses: juliangruber/approve-pull-request-action@v1
      #   with:
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     number: ${{ github.event.number }}

      # - name: Squash Merge
      #   uses: pascalgn/automerge-action@v0.15.3
      #   if: ${{ steps.step_status.outputs.STATUS == 'true' }}
      #   env:
      #     GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      #     MERGE_LABELS: ${{ matrix.label }}
      #     MERGE_REMOVE_LABELS: ${{ matrix.label }}
      #     MERGE_COMMIT_MESSAGE: ${{ matrix.commit_message }}
      #     MERGE_REQUIRED_APPROVALS: 0
      #     MERGE_DELETE_BRANCH: true
      #     MERGE_METHOD: "squash"
      #     MERGE_FORKS: "false"
      #     UPDATE_LABELS: ""
      #     UPDATE_METHOD: "rebase"

      # - name: Notify with Discord Webhook
      #   uses: rjstone/discord-webhook-notify@v1
      #   if: steps.haslabel.outputs.labeled-AutoSquash_Crowdin
      #   with:
      #     severity: info
      #     username: RoadMap-Crowdin
      #     avatarUrl: https://github.githubassets.com/images/modules/logos_page/Octocat.png
      #     description: |
      #       **翻譯已自動進行合併！**
      #       **變動合併資訊**：[#${{ github.event.number }}](https://github.com/SlimeTraditionalTranslation/Misc-Translate/pull/${{ github.event.number }})
      #     footer: "自動化合併通知"
      #     text: "<@292313547227136001>"
      #     webhookUrl: ${{ secrets.DISCORD_WEBHOOK_ADMIN }}

      # - name: Trigger Sync Action
      #   uses: benc-uk/workflow-dispatch@v1
      #   if: steps.haslabel.outputs.labeled-AutoSquash_Crowdin
      #   with:
      #     workflow: RoadMapAction
      #     token: ${{ secrets.EFI_BOT_TOKEN }}
      #     inputs: '{ "ref":"main","chooser":"Sync" }'
